# Generated by Django 4.0 on 2021-12-26 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InitModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='enter correct model name or select from list', max_length=50)),
                ('init_port', models.CharField(help_text='list of necessary ports like: AC1, AC2, DC1', max_length=20)),
                ('additional_port', models.CharField(help_text='list of additional ports like: AC1, AC2, DC1', max_length=30)),
                ('category_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.typeequipment')),
            ],
        ),
    ]
