# Generated by Django 4.0.3 on 2022-04-11 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='real name like "ВВГнг-14х1,5"', max_length=50, unique=True, verbose_name='название')),
                ('code', models.CharField(help_text='system name for scheme initialization like "VVG_NG_1x1,5"', max_length=50, unique=True, verbose_name='код для сборки')),
                ('min_bend_radius', models.PositiveSmallIntegerField(default=0, verbose_name='радиус изгиба')),
                ('thickness', models.FloatField(default=0, verbose_name='толщина кабеля в миллиметрах')),
                ('color', models.CharField(choices=[('MAGENTA', 'Розовый'), ('GREEN', 'Зеленый'), ('BLACK', 'Черный'), ('RED', 'Красный'), ('YELLOW', 'Желтый'), ('BLUE', 'Синий')], default='RED', max_length=40, verbose_name='цвет изображения')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Двигатели', 'Двигатели асинхронные'), ('Давление', 'Датчики давления'), ('Гусары', 'Гусары'), ('Расходомеры', 'Расходомеры'), ('Температура', 'Датчики температуры'), ('Задвижки', 'Задвижки с электроманитным управлением')], default='Двигатели', max_length=40, unique=True, verbose_name='Выберите категории оборудования')),
            ],
        ),
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter correct model name or select from list', max_length=50, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='введите номер проекта, например: "423-18v1"', max_length=12, unique=True, verbose_name='номер проекта')),
                ('description', models.CharField(help_text='опишите проект, например: "Газпром, Салават нефтехим"', max_length=50, unique=True, verbose_name='описание проекта')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='дата')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='SelectedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, null=True, verbose_name='Обозначение на схеме')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.modelname')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='catalog.project')),
            ],
        ),
        migrations.AddField(
            model_name='modelname',
            name='ports',
            field=models.ManyToManyField(to='catalog.port'),
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_symbol', models.SlugField(max_length=12, null=True)),
                ('connect', models.SlugField(max_length=12, null=True)),
                ('cable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cable')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='catalog.selectedmodel')),
                ('port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.port')),
            ],
            options={
                'unique_together': {('cable_symbol', 'connect')},
            },
        ),
    ]
