# Generated by Django 4.0 on 2021-12-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initmodels',
            name='additional_port',
            field=models.CharField(blank=True, help_text='list of additional ports like: AC1, AC2, DC1', max_length=30),
        ),
    ]
