# Generated by Django 4.0 on 2022-01-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_initmodels_additional_port'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeEquipment',
            new_name='Equipment',
        ),
        migrations.RenameModel(
            old_name='InitModels',
            new_name='Init',
        ),
    ]
