# Generated by Django 4.0 on 2022-01-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_typeequipment_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('EA', 'Двигатели асинхронные'), ('SP', 'Датчики давления'), ('G', 'Гусары'), ('EG', 'Расходомеры'), ('CI', 'Кабельные ввода'), ('ST', 'Датчики температуры'), ('A', 'Задвижки с электроманитным управлением')], default='EA', max_length=30),
        ),
    ]
