# Generated by Django 4.0 on 2022-01-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_equipment_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_name', models.CharField(help_text='real name like "ВВГнг-14х1,5"', max_length=50)),
                ('init_name', models.CharField(help_text='system name for scheme initialization like "VVG_NG_1x1,5"', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('Двигатели асинхронные', 'Двигатели асинхронные'), ('Датчики давления', 'Датчики давления'), ('Гусары', 'Гусары'), ('Расходомеры', 'Расходомеры'), ('Кабельные ввода', 'Кабельные ввода'), ('Датчики температуры', 'Датчики температуры'), ('Задвижки с электроманитным управлением', 'Задвижки с электроманитным управлением')], default='EA', max_length=40),
        ),
        migrations.AlterField(
            model_name='init',
            name='init_port',
            field=models.CharField(help_text='necessary port like: AC1, AC2, DC1', max_length=20),
        ),
    ]
