# Generated by Django 4.0 on 2022-01-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_equipment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('Двигатели асинхронные', 'Двигатели асинхронные'), ('Датчики давления', 'Датчики давления'), ('Гусары', 'Гусары'), ('Расходомеры', 'Расходомеры'), ('Кабельные ввода', 'Кабельные ввода'), ('Датчики температуры', 'Датчики температуры'), ('Задвижки с электроманитным управлением', 'Задвижки с электроманитным управлением')], default='EA', max_length=40),
        ),
    ]
