# Generated by Django 4.0 on 2022-01-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_equipment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('Двигатели асинхронные', 'Двигатели асинхронные'), ('Датчики давления', 'Датчики давления'), ('Гусары', 'Гусары'), ('Расходомеры', 'Расходомеры'), ('Кабельные ввода', 'Кабельные ввода'), ('Датчики температуры', 'Датчики температуры'), ('Задвижки с электроманитным управлением', 'Задвижки с электроманитным управлением')], max_length=40, verbose_name='Категории оборудования'),
        ),
    ]
